<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Balonmano\Shared\Middelware\Rate;

use Psr\Http\Message\ServerRequestInterface;

interface ConnectionResolverInterface
{
    public function resolve(ServerRequestInterface $request): string;
}
